### ISSUE TITLE
[Bug]: Django Error

### ISSUE THREAD

**Issue by Lugigiiii** [rehmatworks/fastcp#14]
### Describe the bug / issue

Hey man, your project seems very interesting, so I tried to install it on my server (Ubuntu 20.04 LTS). After getting HTTP Err_Connection_Refused I checked the logs for a while. 
1. One of the admin.py files contains ugettext_lazy which is not used by Django 4 anymore. This results in one of the workers crashing.
2. After fixing that part I was able to see the login page. But when I clicked on Login, no matter what I typed in, I was getting an HTTP 500 error. Checked the logs afterwards but theres nothing to be seen. Couldnt figure out more yet.

Hope this information helps you. I‘ve attached the log output of before I fixed the ugettext part.

### Version

Master

### Is it an error in the frontend (web) or in the backend (system)?

Backend (System)

### Which Ubuntu version?

20.04

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
- The job identifier is 96407.
Feb 19 21:05:49 cotezewh022 gunicorn[102785]: [2022-02-19 21:05:49 +0100] [102785] [INFO] Starting gunicorn 20.1.0
Feb 19 21:05:49 cotezewh022 gunicorn[102785]: [2022-02-19 21:05:49 +0100] [102785] [INFO] Listening at: https://0.0.0.0:2050 (102785)
Feb 19 21:05:49 cotezewh022 gunicorn[102785]: [2022-02-19 21:05:49 +0100] [102785] [INFO] Using worker: uvicorn.workers.UvicornWorker
Feb 19 21:05:49 cotezewh022 gunicorn[102787]: [2022-02-19 21:05:49 +0100] [102787] [INFO] Booting worker with pid: 102787
Feb 19 21:05:49 cotezewh022 gunicorn[102788]: [2022-02-19 21:05:49 +0100] [102788] [INFO] Booting worker with pid: 102788
Feb 19 21:05:49 cotezewh022 gunicorn[102789]: [2022-02-19 21:05:49 +0100] [102789] [INFO] Booting worker with pid: 102789
Feb 19 21:05:50 cotezewh022 gunicorn[102790]: [2022-02-19 21:05:50 +0100] [102790] [INFO] Booting worker with pid: 102790
Feb 19 21:05:51 cotezewh022 gunicorn[102787]: [2022-02-19 20:05:51 +0000] [102787] [ERROR] Exception in worker process
Feb 19 21:05:51 cotezewh022 gunicorn[102787]: Traceback (most recent call last):
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     worker.init_process()
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     super(UvicornWorker, self).init_process()
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     self.load_wsgi()
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     self.wsgi = self.app.wsgi()
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     self.callable = self.load()
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     return self.load_wsgiapp()
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     return util.import_app(self.app_uri)
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     mod = importlib.import_module(module)
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     return _bootstrap._gcd_import(name[level:], package, level)
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django_cron/admin.py", line 5, in <module>
Feb 19 21:05:51 cotezewh022 gunicorn[102787]:     from django.utils.translation import ugettext_lazy as _
Feb 19 21:05:51 cotezewh022 gunicorn[102787]: ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/etc/fastcp/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py)
Feb 19 21:05:51 cotezewh022 gunicorn[102787]: [2022-02-19 20:05:51 +0000] [102787] [INFO] Worker exiting (pid: 102787)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]: [2022-02-19 20:05:51 +0000] [102788] [ERROR] Exception in worker process
Feb 19 21:05:51 cotezewh022 gunicorn[102788]: Traceback (most recent call last):
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     worker.init_process()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     super(UvicornWorker, self).init_process()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     self.load_wsgi()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     self.wsgi = self.app.wsgi()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     self.callable = self.load()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     return self.load_wsgiapp()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     return util.import_app(self.app_uri)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     mod = importlib.import_module(module)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     return _bootstrap._gcd_import(name[level:], package, level)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/fastcp/fastcp/asgi.py", line 16, in <module>
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     application = get_asgi_application()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/core/asgi.py", line 12, in get_asgi_application
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     django.setup(set_prefix=False)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     apps.populate(settings.INSTALLED_APPS)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     app_config.ready()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 27, in ready
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     self.module.autodiscover()
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     autodiscover_modules('admin', register_to=site)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 57, in autodiscover_modules
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     import_module('%s.%s' % (app_config.name, module_to_search))
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     return _bootstrap._gcd_import(name[level:], package, level)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django_cron/admin.py", line 5, in <module>
Feb 19 21:05:51 cotezewh022 gunicorn[102788]:     from django.utils.translation import ugettext_lazy as _
Feb 19 21:05:51 cotezewh022 gunicorn[102788]: ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/etc/fastcp/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py)
Feb 19 21:05:51 cotezewh022 gunicorn[102788]: [2022-02-19 20:05:51 +0000] [102788] [INFO] Worker exiting (pid: 102788)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]: [2022-02-19 20:05:51 +0000] [102789] [ERROR] Exception in worker process
Feb 19 21:05:51 cotezewh022 gunicorn[102789]: Traceback (most recent call last):
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     worker.init_process()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     super(UvicornWorker, self).init_process()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     self.load_wsgi()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     self.wsgi = self.app.wsgi()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     self.callable = self.load()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     return self.load_wsgiapp()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     return util.import_app(self.app_uri)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     mod = importlib.import_module(module)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     return _bootstrap._gcd_import(name[level:], package, level)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/fastcp/fastcp/asgi.py", line 16, in <module>
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     application = get_asgi_application()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/core/asgi.py", line 12, in get_asgi_application
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     django.setup(set_prefix=False)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     apps.populate(settings.INSTALLED_APPS)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     app_config.ready()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 27, in ready
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     self.module.autodiscover()
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     autodiscover_modules('admin', register_to=site)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 57, in autodiscover_modules
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     import_module('%s.%s' % (app_config.name, module_to_search))
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     return _bootstrap._gcd_import(name[level:], package, level)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django_cron/admin.py", line 5, in <module>
Feb 19 21:05:51 cotezewh022 gunicorn[102789]:     from django.utils.translation import ugettext_lazy as _
Feb 19 21:05:51 cotezewh022 gunicorn[102789]: ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/etc/fastcp/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py)
Feb 19 21:05:51 cotezewh022 gunicorn[102789]: [2022-02-19 20:05:51 +0000] [102789] [INFO] Worker exiting (pid: 102789)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]: [2022-02-19 20:05:51 +0000] [102790] [ERROR] Exception in worker process
Feb 19 21:05:51 cotezewh022 gunicorn[102790]: Traceback (most recent call last):
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     worker.init_process()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     super(UvicornWorker, self).init_process()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     self.load_wsgi()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     self.wsgi = self.app.wsgi()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     self.callable = self.load()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     return self.load_wsgiapp()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     return util.import_app(self.app_uri)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     mod = importlib.import_module(module)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     return _bootstrap._gcd_import(name[level:], package, level)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/fastcp/fastcp/asgi.py", line 16, in <module>
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     application = get_asgi_application()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/core/asgi.py", line 12, in get_asgi_application
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     django.setup(set_prefix=False)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     apps.populate(settings.INSTALLED_APPS)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     app_config.ready()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 27, in ready
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     self.module.autodiscover()
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     autodiscover_modules('admin', register_to=site)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 57, in autodiscover_modules
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     import_module('%s.%s' % (app_config.name, module_to_search))
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     return _bootstrap._gcd_import(name[level:], package, level)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/django_cron/admin.py", line 5, in <module>
Feb 19 21:05:51 cotezewh022 gunicorn[102790]:     from django.utils.translation import ugettext_lazy as _
Feb 19 21:05:51 cotezewh022 gunicorn[102790]: ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/etc/fastcp/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py)
Feb 19 21:05:51 cotezewh022 gunicorn[102790]: [2022-02-19 20:05:51 +0000] [102790] [INFO] Worker exiting (pid: 102790)
Feb 19 21:05:51 cotezewh022 gunicorn[102785]: [2022-02-19 21:05:51 +0100] [102785] [WARNING] Worker with pid 102790 was terminated due to signal 15
Feb 19 21:05:51 cotezewh022 gunicorn[102785]: [2022-02-19 21:05:51 +0100] [102785] [WARNING] Worker with pid 102788 was terminated due to signal 15
Feb 19 21:05:51 cotezewh022 gunicorn[102785]: [2022-02-19 21:05:51 +0100] [102785] [WARNING] Worker with pid 102789 was terminated due to signal 15
Feb 19 21:05:52 cotezewh022 gunicorn[102785]: [2022-02-19 21:05:52 +0100] [102785] [INFO] Shutting down: Master
Feb 19 21:05:52 cotezewh022 gunicorn[102785]: [2022-02-19 21:05:52 +0100] [102785] [INFO] Reason: Worker failed to boot.
Feb 19 21:05:52 cotezewh022 systemd[1]: fastcp.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- An ExecStart= process belonging to unit fastcp.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 3.
Feb 19 21:05:52 cotezewh022 systemd[1]: fastcp.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit fastcp.service has entered the 'failed' state with result 'exit-code'.
```

**Comment by Ralumbi** [comment]
What is your current Django Version?
It has been updated recently to version 3.2.12
[Requirements.txt commit](https://github.com/rehmatworks/fastcp/commit/46c85d9b397c2bc0eecaf7e29cd29586391ff50b)

**Comment by Lugigiiii** [comment]
Must be the current version of it. I‘ve installed it using your script so I don‘t really know which version it was.

**Comment by Lugigiiii** [comment]
@Ralumbi  
Aight, so I managed to fix it by manually installing django 3.2.12 in the venv. Your script installs django 4 by default.
Buut now I received a new error in uvicorn which causes the service to crash.


Traceback (most recent call last):
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     worker.init_process()
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     super(UvicornWorker, self).init_process()
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 142, in init_process
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     self.run()
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 84, in run
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     return asyncio.run(self._serve())
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     return loop.run_until_complete(main)
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     return future.result()
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 78, in _serve
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     await server.serve(sockets=self.sockets)
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     config.load()
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/config.py", line 411, in load
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     self.ssl: Optional[ssl.SSLContext] = create_ssl_context(
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:   File "/etc/fastcp/venv/lib/python3.8/site-packages/uvicorn/config.py", line 127, in create_ssl_context
Mar 13 15:59:10 cotezewh022 gunicorn[85478]:     ctx.load_cert_chain(certfile, keyfile, get_password)
Mar 13 15:59:10 cotezewh022 gunicorn[85478]: ssl.SSLError: [SSL] PEM lib (_ssl.c:4046)

**Comment by Ralumbi** [comment]
I am not the maintainer of this project, not actual contributor. The owner is @rehmatworks
